### ISSUE TITLE
Does it support PSI with payloads?

### ISSUE THREAD

**Issue by Aqua-Dream** [encryptogroup/OPPRF-PSI#3]
I'm interested in the paper and is trying to build my own project based on this implementation via git submodule. 
The paper mentions that this protocol easily supports PSI with payloads. However, it seems that there is no implementation that supports payload in this repo. If not, will the repo be updated to support?

Thanks.

**Comment by Oleksandr-Tkachenko** [comment]
Unfortunately, this implementation indeed does not support payloads and we don't plan to add this functionality in the near future. If you plan to implement it though, we would be thankful if you could make a PR.
